name: Deploy to VPS

on:
  workflow_dispatch:  # Permite la ejecución manual
  push:
    branches:
      - main # O la rama que uses para despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev  # Especifica el entorno a utilizar

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      
        
        
      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/flk/ms/Events
            git pull origin main
            git pull origin master
            mkdir -p ready!  # Corregido: mkdir necesita -p para no fallar si el directorio ya existe
            # Aquí puedes agregar otros comandos para construir y reiniciar tu servicio
            sudo systemctl restart nombre-del-servicio
          EOF
