name: Deploy to VPS

on:
  workflow_dispatch:  # Permite la ejecución manual
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Dev  # Especifica el entorno a utilizar

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      
        
        
      - name: Deploy to VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_PORT }} ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/flk/ms
            sudo systemctl stop events
            echo events service stopped
            git pull origin master
            echo pull from github done
            dotnet restore
            echo dotnet package restore done
            mkdir -p ready!
            dotnet publish --configuration Release --output ./publish
            echo compiled!! 
            sudo systemctl start events
            echo events service is running!
          EOF
